# PROPRIEDADES DA PÁGINA
encoding: utf-8
name: PHP-PB
baseurl: "/"
url: http://php-pb.net/
description: Comunidade PHP na Paraíba

permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: 'page:num'
    
# MENU DE NAVEGAÇÃO
navigation:
- text: início
  url: '/'
- text: encontro
  url: '/encontro'
#- text: vagas de emprego
#  url: '/vagas'
#- text: hangouts
#  url: '/hangouts'

future: true
show_drafts: true
markdown: kramdown
highlighter: pygments
